# Generated by Django 4.1 on 2022-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('action', models.CharField(choices=[('ADD_DATA', 'add data'), ('SEARCH', 'search')], max_length=50)),
            ],
        ),
    ]
