# Generated by Django 4.1 on 2022-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('features', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadss',
            name='features',
        ),
    ]
